(function () {
  var definitions = {
    projects: { label: 'Projects', fields: [['title','Title','text',true],['description','Short description','textarea',true],['technologies','Technologies (comma separated)','text',false],['url','Live or GitHub URL','url',false],['thumbnail','Thumbnail URL or uploaded image','text',false],['published','Published','checkbox',false],['order','Display order','number',false]] },
    certifications: { label: 'Certifications', fields: [['title','Certificate name','text',true],['organization','Issuing organization','text',false],['date','Issue date','date',false],['url','Credential URL','url',false],['published','Published','checkbox',false],['order','Display order','number',false]] },
    gallery: { label: 'Gallery', fields: [['title','Title','text',true],['caption','Caption','textarea',false],['category','Category','text',false],['image','Image URL or uploaded image','text',true],['published','Published','checkbox',false],['order','Display order','number',false]] },
    achievements: { label: 'Achievements', fields: [['title','Title','text',true],['description','Description','textarea',false],['organization','Organization','text',false],['date','Date','date',false],['url','URL','url',false],['published','Published','checkbox',false],['order','Display order','number',false]] },
    experience: { label: 'Experience', fields: [['organization','Organization','text',true],['position','Position','text',true],['location','Location','text',false],['startDate','Start date','date',false],['endDate','End date','date',false],['current','Currently working','checkbox',false],['description','Description','textarea',false],['technologies','Technologies','text',false],['published','Published','checkbox',false],['order','Display order','number',false]] },
    education: { label: 'Education', fields: [['institution','Institution','text',true],['degree','Degree','text',true],['branch','Branch','text',false],['startYear','Start year','number',false],['endYear','End year','number',false],['grade','CGPA / grade','text',false],['description','Description','textarea',false],['published','Published','checkbox',false],['order','Display order','number',false]] },
    skills: { label: 'Skills', fields: [['name','Skill','text',true],['category','Category','text',true],['level','Level (0-100)','number',false],['order','Display order','number',false]] },
    messages: { label: 'Messages', fields: [['name','Name','text',true],['email','Email','email',true],['subject','Subject','text',false],['message','Message','textarea',true],['read','Read','checkbox',false]] },
    profile: { label: 'Profile', fields: [['name','Name','text',true],['headline','Headline','text',false],['bio','Bio','textarea',false],['location','Location','text',false],['email','Email','email',false],['phone','Phone','tel',false],['resume','Resume URL','url',false],['socialLinks','Social links','textarea',false]] },
    settings: { label: 'Settings', fields: [['theme','Theme','text',false],['siteTitle','Site title','text',false],['siteDescription','Site description','textarea',false]] }
  };
  var active = 'projects'; var editing = null;
  function key(type) { return type === 'projects' ? 'rohanPortfolioProjects' : 'rohanPortfolio_' + type; }
  function records(type) { return JSON.parse(localStorage.getItem(key(type)) || '[]'); }
  function save(type, values) { localStorage.setItem(key(type), JSON.stringify(values)); }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]; }); }
  function isLoggedIn() { return sessionStorage.getItem('rohanAdminSession') === 'active'; }
  function renderStats() { var all = Object.keys(definitions).map(function (type) { return { label: definitions[type].label, count: records(type).length }; }); document.getElementById('stats').innerHTML = all.slice(0, 8).map(function (item) { return '<div class="stat"><strong>' + item.count + '</strong><span>' + item.label + '</span></div>'; }).join(''); }
  function renderNav() { document.getElementById('admin-nav').innerHTML = Object.keys(definitions).map(function (type) { return '<button class="' + (type === active ? 'active' : '') + '" data-type="' + type + '">' + definitions[type].label + '</button>'; }).join(''); document.querySelectorAll('[data-type]').forEach(function (button) { button.onclick = function () { active = button.dataset.type; editing = null; render(); }; }); }
  function render() { renderStats(); renderNav(); var definition = definitions[active]; var data = records(active); document.getElementById('content').innerHTML = '<div class="panel-head"><div><p class="eyebrow">Manage content</p><h2>' + definition.label + '</h2></div><button class="button primary" id="add">Add ' + definition.label.slice(0, -1) + '</button></div><div class="rows">' + (data.length ? data.map(function (item, index) { return '<div class="row"><div><strong>' + esc(item.title || item.name || item.position || item.institution || 'Untitled') + '</strong><br><small>' + (item.published === false ? 'Draft' : 'Published') + ' · order ' + (item.order || index + 1) + '</small></div><div class="row-actions"><button data-edit="' + index + '">Edit</button><button data-toggle="' + index + '">' + (item.published === false ? 'Publish' : 'Unpublish') + '</button><button data-delete="' + index + '">Delete</button></div></div>'; }).join('') : '<p>No entries yet. Add the first one to begin.</p>') + '</div><div id="editor"></div>';
    document.getElementById('add').onclick = function () { editing = null; renderEditor(); }; document.querySelectorAll('[data-edit]').forEach(function (b) { b.onclick = function () { editing = Number(b.dataset.edit); renderEditor(); }; }); document.querySelectorAll('[data-delete]').forEach(function (b) { b.onclick = function () { if (confirm('Delete this entry?')) { var data = records(active); data.splice(Number(b.dataset.delete), 1); save(active, data); render(); } }; }); document.querySelectorAll('[data-toggle]').forEach(function (b) { b.onclick = function () { var data = records(active); var item = data[Number(b.dataset.toggle)]; item.published = item.published === false; save(active, data); render(); }; });
  }
  function renderEditor() { var definition = definitions[active]; var item = editing === null ? {} : records(active)[editing]; document.getElementById('editor').innerHTML = '<form class="form" id="entry-form">' + definition.fields.map(function (field) { var value = item[field[0]]; if (field[2] === 'checkbox') return '<label class="check"><input name="' + field[0] + '" type="checkbox" ' + (value ? 'checked' : '') + '>' + field[1] + '</label>'; return '<div class="field ' + (field[2] === 'textarea' ? 'full' : '') + '"><label>' + field[1] + '</label>' + (field[2] === 'textarea' ? '<textarea name="' + field[0] + '" ' + (field[3] ? 'required' : '') + '>' + esc(value) + '</textarea>' : '<input name="' + field[0] + '" type="' + field[2] + '" value="' + esc(value) + '" ' + (field[3] ? 'required' : '') + '>') + '</div>'; }).join('') + '<div class="hero-actions full"><button class="button primary" type="submit">Save</button><button class="button" type="button" id="cancel">Cancel</button><label class="button"><input id="upload" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" hidden> Upload file</label></div></form>'; document.getElementById('cancel').onclick = function () { document.getElementById('editor').innerHTML = ''; }; document.getElementById('upload').onchange = handleUpload; document.getElementById('entry-form').onsubmit = function (event) { event.preventDefault(); var result = {}; new FormData(event.target).forEach(function (value, field) { result[field] = value; }); definition.fields.filter(function (field) { return field[2] === 'checkbox'; }).forEach(function (field) { result[field[0]] = event.target.elements[field[0]].checked; }); var data = records(active); if (editing === null) data.push(result); else data[editing] = result; save(active, data); editing = null; render(); }; }
  function handleUpload(event) { var file = event.target.files[0]; var allowed = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf']; if (!file || allowed.indexOf(file.type) === -1 || file.size > 5 * 1024 * 1024) return alert('Choose a JPG, PNG, WEBP or PDF file up to 5 MB.'); var reader = new FileReader(); reader.onload = function () { var field = document.querySelector('[name="thumbnail"], [name="image"], [name="certificate"]'); if (field) field.value = reader.result; }; reader.readAsDataURL(file); }
  var authForm = document.getElementById('auth-form'); var hasPassword = Boolean(localStorage.getItem('rohanAdminPassword')); document.getElementById('auth-title').textContent = hasPassword ? 'Admin access' : 'Create local admin'; document.getElementById('auth-submit').textContent = hasPassword ? 'Log in' : 'Set password'; authForm.onsubmit = function (event) { event.preventDefault(); var password = document.getElementById('password').value; if (!hasPassword) { localStorage.setItem('rohanAdminPassword', password); hasPassword = true; } else if (password !== localStorage.getItem('rohanAdminPassword')) { document.getElementById('auth-message').textContent = 'Password does not match.'; return; } sessionStorage.setItem('rohanAdminSession', 'active'); showApp(); }; document.getElementById('logout').onclick = function () { sessionStorage.removeItem('rohanAdminSession'); location.reload(); }; function showApp() { document.getElementById('auth').classList.add('hidden'); document.getElementById('app').classList.remove('hidden'); render(); } if (isLoggedIn()) showApp();
}());
